kind: Service
apiVersion: v1
metadata:
  name: springboot-demo-app
  labels:
    name: springboot-demo-app
spec:
  ports:
    - nodePort: 30163
      port: 80
      targetPort: 8900
      protocol: TCP
  selector:
    app: 8900

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-demo-app
spec:
  selector:
    matchLabels:
      app: springboot-demo-app
  replicas: 2
  template:
    metadata:
      labels:
        app: springboot-demo-app
    spec:
      containers:
        - name: springboot-demo-app
          image: ousmane1999/spring-demo:latest
          ports:
            - containerPort: 8900
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials # Secret Name
                  key: postgres_user
            - name: POSTGRES_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
